name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt install --no-install-recommends libcmocka-dev bmake
          echo "CFLAGS=-fPIC" >> $GITHUB_ENV        
      - name: Build libuuid
        run: bmake
      - name: Run tests
        run: bmake test
